### ISSUE TITLE
About @Controller

### ISSUE THREAD

**Issue by detDaYe** [detDaYe/ks-web#1]
IndexController 클래스에 Controller 어노테이션을 적지 않아야 웹 페이지가 정상적으로 표시되는 현상이 발생

에러 로그 일부 : 
template might not exist or might not be accessible by any of the configured Template Resolvers ...

**Comment by sigmadream** [comment]
1. index.html  파일이 위치한 리소스 폴더 확인하세요
2. F* 워드를 github에 남겨두시면 히스토리가 검색되기 때문에 좋은 습관이 아니니 주석은 지우는것을 고려해보세요.

**Comment by detDaYe** [comment]
1. index.html의 위치가 잘못된 폴더에 있던 것을 확인!
2. 주의하겠습니다
